# Extent of the area of interest
minx: -90.0955545723
miny: 13.1490168319
maxx: -87.7235029772
maxy: 14.4241327987

# flow files
base_max_file: test/base_max.csv
flow_value_source: return_period # Two options: return_period, historical
flow_file: test/flows.csv
return_period: 100
date_start: 2000-01-01
date_end: 2000-01-31

# output folders
# dem folders
dem_dir: test/dems
output_dem: test/dem.tif

# streamlines folders
streamlines_dir: test/streamlines
output_streamlines: test/streamlines.parquet
streamlines_raster_dir: test/streamlines_raster
output_streams: test/streams.tif

# land use folders
land_use_dir: test/land_use
output_land_use: test/land_use.tif
land_use_text_file: ESA_land_use.txt

# ARC Required files
main_input_file: test/mifn.txt
vdt_file: test/vdt.txt
flood_map: test/flood_map.tif

# Optional files
curve_file: ''
meta_file: ''
cross_section_file: ''

# Parameters
set_depth: 0

cross_section_distance: 4000
degree_manipulation: 6.1
degree_interval: 1.5
low_spot_range: 5
direction_distance: 5
slope_distance: 1
land_use_water_value: 80
vdt_iterations: 15
banks_from_land_use: False
reach_average_curves: False
create_shp_file: False
q_fraction: 1.01
top_width_max_limit: 4000
top_width_factor: 3
flood_local: False
flood_obvious_stream_cells: True

# Bathymetry, optional
output_bathymetry: 'test/bathy.tif'
bathy_trap_h: 0.2
bathy_use_banks: True

output_c2f_bathymetry: ''
