name: arc
channels:
  - conda-forge
  - defaults
dependencies:
  - boto3
  - dask
  - fsspec
  - gdal
  - geopandas
  - libgdal-arrow-parquet
  - numba=0.60
  - python
  - pyarrow
  - pyyaml
  - python
  - s3fs
  - tqdm
  - xarray
  - zarr>=3
